service: serverless-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get

resources:
  Resources:
    ArticlesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: articleId
            AttributeType: S
        KeySchema:
          -
            AttributeName: articleId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: articles